const DB_INITIALIZED_SIGNATURE = 'isDBInitialized';
const USER_PUZZLE_LIST_SIGNATURE = 'userPuzzleList';
const USER_PUZZLE_DETAILS_SIGNATURE = 'userPuzzleNo';

export {
  DB_INITIALIZED_SIGNATURE,
  USER_PUZZLE_LIST_SIGNATURE,
  USER_PUZZLE_DETAILS_SIGNATURE,
};
