const puzzles = [
  {
    id: 0,
    name: 'Smile',
    maxLives: 3,
    currentLives: 3,
    boardData: {
      width: 5,
      height: 5,
      fields: [
        [
          {hasPixel: false},
          {hasPixel: true, color: '#f0f0f0'},
          {hasPixel: false},
          {hasPixel: true, color: '#f0f0f0'},
          {hasPixel: false},
        ],
        [
          {hasPixel: false},
          {hasPixel: true, color: '#080808'},
          {hasPixel: false},
          {hasPixel: true, color: '#080808'},
          {hasPixel: false},
        ],
        [
          {hasPixel: false},
          {hasPixel: false},
          {hasPixel: false},
          {hasPixel: false},
          {hasPixel: false},
        ],
        [
          {hasPixel: true, color: '#d02020'},
          {hasPixel: false},
          {hasPixel: false},
          {hasPixel: false},
          {hasPixel: true, color: '#d02020'},
        ],
        [
          {hasPixel: false},
          {hasPixel: true, color: '#d02020'},
          {hasPixel: true, color: '#d02020'},
          {hasPixel: true, color: '#d02020'},
          {hasPixel: false},
        ],
      ],
    },
  },
  {
    id: 1,
    name: 'Five',
    maxLives: 3,
    currentLives: 3,
    boardData: {
      width: 5,
      height: 5,
      fields: [
        [
          {hasPixel: false},
          {hasPixel: true},
          {hasPixel: true},
          {hasPixel: true},
          {hasPixel: false},
        ],
        [
          {hasPixel: false},
          {hasPixel: true},
          {hasPixel: false},
          {hasPixel: false},
          {hasPixel: false},
        ],
        [
          {hasPixel: false},
          {hasPixel: true},
          {hasPixel: true},
          {hasPixel: true},
          {hasPixel: false},
        ],
        [
          {hasPixel: false},
          {hasPixel: false},
          {hasPixel: false},
          {hasPixel: true},
          {hasPixel: false},
        ],
        [
          {hasPixel: false},
          {hasPixel: true},
          {hasPixel: true},
          {hasPixel: true},
          {hasPixel: false},
        ],
      ],
    },
  },
  {
    id: 2,
    name: 'Magical Wolf',
    maxLives: 3,
    currentLives: 3,
    boardData: {
      width: 5,
      height: 5,
      fields: [
        [
          {hasPixel: false},
          {hasPixel: false},
          {hasPixel: true, color: '#101060'},
          {hasPixel: true, color: '#101060'},
          {hasPixel: true, color: '#d0d010'},
        ],
        [
          {hasPixel: true, color: '#202020'},
          {hasPixel: true, color: '#101060'},
          {hasPixel: true, color: '#101060'},
          {hasPixel: true, color: '#101060'},
          {hasPixel: true, color: '#202020'},
        ],
        [
          {hasPixel: true, color: '#202020'},
          {hasPixel: true, color: '#202020'},
          {hasPixel: true, color: '#202020'},
          {hasPixel: true, color: '#202020'},
          {hasPixel: true, color: '#202020'},
        ],
        [
          {hasPixel: true, color: '#202020'},
          {hasPixel: true, color: '#a01010'},
          {hasPixel: true, color: '#202020'},
          {hasPixel: true, color: '#a01010'},
          {hasPixel: true, color: '#202020'},
        ],
        [
          {hasPixel: true, color: '#202020'},
          {hasPixel: true, color: '#202020'},
          {hasPixel: true, color: '#202020'},
          {hasPixel: true, color: '#202020'},
          {hasPixel: true, color: '#202020'},
        ],
      ],
    },
  },
  {
    id: 3,
    name: 'Chick',
    maxLives: 3,
    currentLives: 3,
    boardData: {
      width: 5,
      height: 5,
      fields: [
        [
          {hasPixel: false},
          {hasPixel: true, color: '#020202'},
          {hasPixel: true, color: '#d0d010'},
          {hasPixel: false},
          {hasPixel: false},
        ],
        [
          {hasPixel: true, color: '#d08020'},
          {hasPixel: true, color: '#d08020'},
          {hasPixel: true, color: '#d0d010'},
          {hasPixel: false},
          {hasPixel: false},
        ],
        [
          {hasPixel: false},
          {hasPixel: true, color: '#d0d010'},
          {hasPixel: true, color: '#d0d010'},
          {hasPixel: true, color: '#d0d010'},
          {hasPixel: true, color: '#d0d010'},
        ],
        [
          {hasPixel: false},
          {hasPixel: false},
          {hasPixel: true, color: '#654321'},
          {hasPixel: false},
          {hasPixel: false},
        ],
        [
          {hasPixel: false},
          {hasPixel: true, color: '#654321'},
          {hasPixel: true, color: '#654321'},
          {hasPixel: false},
          {hasPixel: false},
        ],
      ],
    },
  },
];

export default puzzles;
