const puzzles = [
  {
    name: 'Smile',
    maxLives: 3,
    boardWidth: 5,
    boardHeight: 5,
    fields: [
      [
        {hasPixel: false},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: false},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#080808'},
        {hasPixel: false},
        {hasPixel: true, color: '#080808'},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: true, color: '#d02020'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#d02020'},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: false},
      ],
    ],
  },
  {
    name: 'Five',
    maxLives: 3,
    boardWidth: 5,
    boardHeight: 5,
    fields: [
      [
        {hasPixel: false},
        {hasPixel: true},
        {hasPixel: true},
        {hasPixel: true},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true},
        {hasPixel: true},
        {hasPixel: true},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true},
        {hasPixel: true},
        {hasPixel: true},
        {hasPixel: false},
      ],
    ],
  },
  {
    name: 'Magical Wolf',
    maxLives: 3,
    boardWidth: 5,
    boardHeight: 5,
    fields: [
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#101060'},
        {hasPixel: true, color: '#101060'},
        {hasPixel: true, color: '#d0d010'},
      ],
      [
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#101060'},
        {hasPixel: true, color: '#101060'},
        {hasPixel: true, color: '#101060'},
        {hasPixel: true, color: '#202020'},
      ],
      [
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#202020'},
      ],
      [
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#a01010'},
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#a01010'},
        {hasPixel: true, color: '#202020'},
      ],
      [
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#202020'},
      ],
    ],
  },
  {
    name: 'Chick',
    maxLives: 3,
    boardWidth: 5,
    boardHeight: 5,
    fields: [
      [
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#d0d010'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: true, color: '#d08020'},
        {hasPixel: true, color: '#d08020'},
        {hasPixel: true, color: '#d0d010'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#d0d010'},
        {hasPixel: true, color: '#d0d010'},
        {hasPixel: true, color: '#d0d010'},
        {hasPixel: true, color: '#d0d010'},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#654321'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#654321'},
        {hasPixel: true, color: '#654321'},
        {hasPixel: false},
        {hasPixel: false},
      ],
    ],
  },
  {
    name: 'Pick',
    maxLives: 3,
    boardWidth: 5,
    boardHeight: 5,
    fields: [
      [
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
      ],
      [
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: true, color: '#654321'},
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#654321'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#654321'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#654321'},
        {hasPixel: false},
        {hasPixel: false},
      ],
    ],
  },
  {
    name: 'Boat',
    maxLives: 3,
    boardWidth: 5,
    boardHeight: 5,
    fields: [
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: true, color: '#654321'},
        {hasPixel: true, color: '#654321'},
        {hasPixel: true, color: '#654321'},
        {hasPixel: true, color: '#654321'},
        {hasPixel: true, color: '#654321'},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#654321'},
        {hasPixel: true, color: '#654321'},
        {hasPixel: true, color: '#654321'},
        {hasPixel: true, color: '#654321'},
      ],
    ],
  },
  {
    name: 'Fork',
    maxLives: 3,
    boardWidth: 5,
    boardHeight: 5,
    fields: [
      [
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
      ],
      [
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
      ],
      [
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#020202'},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: false},
      ],
    ],
  },
  {
    name: 'Love',
    maxLives: 3,
    boardWidth: 5,
    boardHeight: 5,
    fields: [
      [
        {hasPixel: false},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: false},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: false},
      ],
      [
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
      ],
      [
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: false},
        {hasPixel: false},
      ],
    ],
  },
  {
    name: 'Saturn',
    maxLives: 3,
    boardWidth: 5,
    boardHeight: 5,
    fields: [
      [
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
      ],
    ],
  } /*
  {
    name: 'BLANK',
    maxLives: 3,
    boardWidth: 5,
    boardHeight: 5,
    fields: [
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
    ],
  },*/,
];

export default puzzles;
