const puzzles = [
  {
    name: 'Smile',
    maxLives: 3,
    boardWidth: 5,
    boardHeight: 5,
    fields: [
      [
        {hasPixel: false},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: false},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#080808'},
        {hasPixel: false},
        {hasPixel: true, color: '#080808'},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: true, color: '#d02020'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#d02020'},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: false},
      ],
    ],
  },
  {
    name: 'Five',
    maxLives: 3,
    boardWidth: 5,
    boardHeight: 5,
    fields: [
      [
        {hasPixel: false},
        {hasPixel: true},
        {hasPixel: true},
        {hasPixel: true},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true},
        {hasPixel: true},
        {hasPixel: true},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true},
        {hasPixel: true},
        {hasPixel: true},
        {hasPixel: false},
      ],
    ],
  },
  {
    name: 'Magical Wolf',
    maxLives: 3,
    boardWidth: 5,
    boardHeight: 5,
    fields: [
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#101060'},
        {hasPixel: true, color: '#101060'},
        {hasPixel: true, color: '#d0d010'},
      ],
      [
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#101060'},
        {hasPixel: true, color: '#101060'},
        {hasPixel: true, color: '#101060'},
        {hasPixel: true, color: '#202020'},
      ],
      [
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#202020'},
      ],
      [
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#a01010'},
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#a01010'},
        {hasPixel: true, color: '#202020'},
      ],
      [
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#202020'},
        {hasPixel: true, color: '#202020'},
      ],
    ],
  },
  {
    name: 'Chick',
    maxLives: 3,
    boardWidth: 5,
    boardHeight: 5,
    fields: [
      [
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#d0d010'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: true, color: '#d08020'},
        {hasPixel: true, color: '#d08020'},
        {hasPixel: true, color: '#d0d010'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#d0d010'},
        {hasPixel: true, color: '#d0d010'},
        {hasPixel: true, color: '#d0d010'},
        {hasPixel: true, color: '#d0d010'},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#654321'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#654321'},
        {hasPixel: true, color: '#654321'},
        {hasPixel: false},
        {hasPixel: false},
      ],
    ],
  },
  {
    name: 'Pick',
    maxLives: 3,
    boardWidth: 5,
    boardHeight: 5,
    fields: [
      [
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
      ],
      [
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: true, color: '#654321'},
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#654321'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#654321'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#654321'},
        {hasPixel: false},
        {hasPixel: false},
      ],
    ],
  },
  {
    name: 'Boat',
    maxLives: 3,
    boardWidth: 5,
    boardHeight: 5,
    fields: [
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: true, color: '#654321'},
        {hasPixel: true, color: '#654321'},
        {hasPixel: true, color: '#654321'},
        {hasPixel: true, color: '#654321'},
        {hasPixel: true, color: '#654321'},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#654321'},
        {hasPixel: true, color: '#654321'},
        {hasPixel: true, color: '#654321'},
        {hasPixel: true, color: '#654321'},
      ],
    ],
  },
  {
    name: 'Fork',
    maxLives: 3,
    boardWidth: 5,
    boardHeight: 5,
    fields: [
      [
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
      ],
      [
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
      ],
      [
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#020202'},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: false},
      ],
    ],
  },
  {
    name: 'Love',
    maxLives: 3,
    boardWidth: 5,
    boardHeight: 5,
    fields: [
      [
        {hasPixel: false},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: false},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: false},
      ],
      [
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
      ],
      [
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#d02020'},
        {hasPixel: false},
        {hasPixel: false},
      ],
    ],
  },
  {
    name: 'Saturn',
    maxLives: 3,
    boardWidth: 5,
    boardHeight: 5,
    fields: [
      [
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#020202'},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
        {hasPixel: true, color: '#020202'},
        {hasPixel: false},
      ],
    ],
  },
  {
    name: 'Cross',
    maxLives: 3,
    boardWidth: 3,
    boardHeight: 3,
    fields: [
      [{hasPixel: true}, {hasPixel: false}, {hasPixel: true}],
      [{hasPixel: false}, {hasPixel: true}, {hasPixel: false}],
      [{hasPixel: true}, {hasPixel: false}, {hasPixel: true}],
    ],
  },
  {
    name: 'Sword',
    maxLives: 3,
    boardWidth: 12,
    boardHeight: 12,
    fields: [
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#352732'},
        {hasPixel: true, color: '#352732'},
        {hasPixel: true, color: '#352732'},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#352732'},
        {hasPixel: true, color: '#fcfcfc'},
        {hasPixel: true, color: '#fcfcfc'},
        {hasPixel: true, color: '#fcfcfc'},
        {hasPixel: true, color: '#352732'},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#352732'},
        {hasPixel: true, color: '#fcfcfc'},
        {hasPixel: true, color: '#fcfcfc'},
        {hasPixel: true, color: '#9e95cf'},
        {hasPixel: true, color: '#c2cada'},
        {hasPixel: true, color: '#352732'},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#352732'},
        {hasPixel: true, color: '#fcfcfc'},
        {hasPixel: true, color: '#fcfcfc'},
        {hasPixel: true, color: '#9e95cf'},
        {hasPixel: true, color: '#c2cada'},
        {hasPixel: true, color: '#c2cada'},
        {hasPixel: true, color: '#352732'},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#352732'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#352732'},
        {hasPixel: true, color: '#fcfcfc'},
        {hasPixel: true, color: '#fcfcfc'},
        {hasPixel: true, color: '#9e95cf'},
        {hasPixel: true, color: '#c2cada'},
        {hasPixel: true, color: '#c2cada'},
        {hasPixel: true, color: '#352732'},
        {hasPixel: false},
      ],
      [
        {hasPixel: true, color: '#352732'},
        {hasPixel: true, color: '#e9b51c'},
        {hasPixel: true, color: '#352732'},
        {hasPixel: true, color: '#352732'},
        {hasPixel: true, color: '#fcfcfc'},
        {hasPixel: true, color: '#fcfcfc'},
        {hasPixel: true, color: '#9e95cf'},
        {hasPixel: true, color: '#c2cada'},
        {hasPixel: true, color: '#c2cada'},
        {hasPixel: true, color: '#352732'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: true, color: '#352732'},
        {hasPixel: true, color: '#e9b51c'},
        {hasPixel: true, color: '#e9b51c'},
        {hasPixel: true, color: '#352732'},
        {hasPixel: true, color: '#fcfcfc'},
        {hasPixel: true, color: '#9e95cf'},
        {hasPixel: true, color: '#c2cada'},
        {hasPixel: true, color: '#c2cada'},
        {hasPixel: true, color: '#352732'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#352732'},
        {hasPixel: true, color: '#bb8228'},
        {hasPixel: true, color: '#e9b51c'},
        {hasPixel: true, color: '#9e95cf'},
        {hasPixel: true, color: '#c2cada'},
        {hasPixel: true, color: '#c2cada'},
        {hasPixel: true, color: '#352732'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#352732'},
        {hasPixel: true, color: '#463e3e'},
        {hasPixel: true, color: '#28b8fe'},
        {hasPixel: true, color: '#e9b51c'},
        {hasPixel: true, color: '#9e95cf'},
        {hasPixel: true, color: '#352732'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: true, color: '#352732'},
        {hasPixel: true, color: '#463e3e'},
        {hasPixel: true, color: '#585752'},
        {hasPixel: true, color: '#463e3e'},
        {hasPixel: true, color: '#bb8228'},
        {hasPixel: true, color: '#e9b51c'},
        {hasPixel: true, color: '#352732'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: true, color: '#352732'},
        {hasPixel: true, color: '#585752'},
        {hasPixel: true, color: '#463e3e'},
        {hasPixel: true, color: '#352732'},
        {hasPixel: true, color: '#352732'},
        {hasPixel: true, color: '#e9b51c'},
        {hasPixel: true, color: '#e9b51c'},
        {hasPixel: true, color: '#352732'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#352732'},
        {hasPixel: true, color: '#352732'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#352732'},
        {hasPixel: true, color: '#352732'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
    ],
  },
  {
    name: 'Holy Warrior',
    maxLives: 8,
    boardWidth: 32,
    boardHeight: 32,
    fields: [
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#909090'},
        {hasPixel: true, color: '#a0a0a0'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#909090'},
        {hasPixel: true, color: '#a0a0a0'},
        {hasPixel: true, color: '#a0a0a0'},
        {hasPixel: true, color: '#909090'},
        {hasPixel: true, color: '#909090'},
        {hasPixel: true, color: '#a0a0a0'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: false},
        {hasPixel: true, color: '#909090'},
        {hasPixel: true, color: '#a0a0a0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#909090'},
        {hasPixel: true, color: '#ca8f72'},
        {hasPixel: true, color: '#e5a282'},
        {hasPixel: true, color: '#a0a0a0'},
        {hasPixel: true, color: '#909090'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: false},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#a0a0a0'},
        {hasPixel: true, color: '#ca8f72'},
        {hasPixel: true, color: '#7f5a48'},
        {hasPixel: true, color: '#e5a282'},
        {hasPixel: true, color: '#7f5a48'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#a0a0a0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#ca8f72'},
        {hasPixel: true, color: '#e5a282'},
        {hasPixel: true, color: '#e5a282'},
        {hasPixel: true, color: '#e5a282'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: false},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#c0a040'},
        {hasPixel: true, color: '#f2c44d'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#a5765e'},
        {hasPixel: true, color: '#ca8f72'},
        {hasPixel: true, color: '#e5a282'},
        {hasPixel: true, color: '#a5765e'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#f2c44d'},
        {hasPixel: true, color: '#c0a040'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#c0a040'},
        {hasPixel: true, color: '#c0a040'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#303030'},
        {hasPixel: true, color: '#303030'},
        {hasPixel: true, color: '#303030'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#c0a040'},
        {hasPixel: true, color: '#c0a040'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: true, color: '#c00000'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: true, color: '#c00000'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#303030'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: true, color: '#c00000'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#303030'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: true, color: '#c00000'},
        {hasPixel: true, color: '#c00000'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: false},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: true, color: '#c00000'},
        {hasPixel: true, color: '#c00000'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: false},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#c00000'},
        {hasPixel: true, color: '#c00000'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#a05000'},
        {hasPixel: true, color: '#c06000'},
        {hasPixel: true, color: '#f8e060'},
        {hasPixel: true, color: '#f8e060'},
        {hasPixel: true, color: '#c06000'},
        {hasPixel: true, color: '#a05000'},
        {hasPixel: true, color: '#303030'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#aa8834'},
        {hasPixel: true, color: '#f2c44d'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f3f3f3'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#c0a040'},
        {hasPixel: true, color: '#c0a040'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#f2c44d'},
        {hasPixel: true, color: '#f2c44d'},
        {hasPixel: true, color: '#f2c44d'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#f2c44d'},
        {hasPixel: true, color: '#aa8834'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: true, color: '#c00000'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: false},
        {hasPixel: true, color: '#c0a040'},
        {hasPixel: true, color: '#c0a040'},
        {hasPixel: true, color: '#c0a040'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#f2c44d'},
        {hasPixel: true, color: '#f2c44d'},
        {hasPixel: true, color: '#f2c44d'},
        {hasPixel: false},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#c00000'},
        {hasPixel: true, color: '#c00000'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#c0a040'},
        {hasPixel: true, color: '#c0a040'},
        {hasPixel: true, color: '#c0a040'},
        {hasPixel: false},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#c00000'},
        {hasPixel: true, color: '#c00000'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#c00000'},
        {hasPixel: true, color: '#c00000'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#303030'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: false},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#c00000'},
        {hasPixel: true, color: '#c00000'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: false},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#c00000'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#c00000'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#303030'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#c00000'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#ffffff'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#f0f0f0'},
        {hasPixel: true, color: '#e00000'},
        {hasPixel: false},
        {hasPixel: true, color: '#303030'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#303030'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#303030'},
        {hasPixel: true, color: '#303030'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: true, color: '#d0d0d0'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#303030'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#303030'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#303030'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#b0b0b0'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#303030'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: true, color: '#808080'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#505050'},
        {hasPixel: true, color: '#303030'},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
    ],
  },

  /*
  {
    name: 'BLANK',
    maxLives: 3,
    boardWidth: 5,
    boardHeight: 5,
    fields: [
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
      [
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
        {hasPixel: false},
      ],
    ],
  },*/

  ,
  ,
];

export default puzzles;
